# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - bicep/resourceGroups/pipeline/**

variables:
- group: resource-group-variables

jobs:
- job: test_and_bicep_what_if
  pool:
    vmImage: windows-latest
  steps:
  - task: ps-rule-install@2
    inputs:
      module: 'PSRule.Rules.Azure'
      latest: false
      prerelease: false
  - task: ps-rule-assert@2
    inputs:
      inputType: 'inputPath'
      inputPath: './bicep/resourceGroups/deploy.bicep'
      modules: 'PSRule.Rules.Azure'
      outputFormat: 'Sarif'
      outputPath: 'psrule-results'
  - task: PowerShell@2
    displayName: login to azure
    inputs:
      targetType: 'inline'
      script: |
        az login --service-principal --username $(client_id) --password $(client_secret) --tenant $(tenant_id)
  - task: PowerShell@2
    displayName: run bicep what-if
    inputs:
      targetType: 'inline'
      script: |
        cd ./bicep/resourceGroups/
        az deployment sub what-if --template-file .\deploy.bicep --parameters .\config\parameters.json -l australiaeast

- job: manual_approval
  displayName: "Manual Approval"
  dependsOn: test_and_bicep_what_if
  pool: server
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 5
    inputs:
      notifyUsers: 'kennyo+pipeline@pm.me'
      instructions: 'Check PSRule and What-If output'
